// apps/web/src/lib/components/dashboard/LowStockAlerts.svelte
<script lang="ts">
    import {
        Card,
        CardContent,
        CardHeader,
        CardTitle,
    } from "$lib/components/ui/card";
    import { AlertCircle, ArrowUpRight, PackageOpen } from "@lucide/svelte";
    import { cn } from "$lib/utils";
    import { Button } from "$lib/components/ui/button";

    const lowStockProducts = [
        {
            id: 1,
            name: "Loreal Shampoo",
            stock: 3,
            minStock: 10,
            status: "critical",
        },
        {
            id: 2,
            name: "Hair Dye #5",
            stock: 5,
            minStock: 15,
            status: "warning",
        },
        {
            id: 3,
            name: "Hairspray Extra",
            stock: 8,
            minStock: 20,
            status: "warning",
        },
        {
            id: 4,
            name: "Conditioner Repair",
            stock: 2,
            minStock: 10,
            status: "critical",
        },
    ];
</script>

<Card
    class="border border-border/60 shadow-sm rounded-xl bg-white overflow-hidden"
>
    <CardHeader
        class="flex flex-row items-center justify-between pb-3 border-b border-border/30 space-y-0 bg-gray-50/30"
    >
        <CardTitle class="text-sm font-semibold text-foreground tracking-tight">
            Sắp hết hàng
        </CardTitle>
        <Button
            variant="ghost"
            size="icon"
            class="h-8 w-8 -mr-2 text-primary hover:bg-primary/5 hover:text-primary"
        >
            <ArrowUpRight class="h-4 w-4" />
        </Button>
    </CardHeader>
    <CardContent class="p-0">
        {#each lowStockProducts as product}
            <div
                class="flex items-center gap-3 px-5 py-4 hover:bg-purple-50/30 transition-colors border-b border-border/30 last:border-0 group"
            >
                <div
                    class={cn(
                        "flex items-center justify-center h-9 w-9 rounded-xl transition-all shadow-sm",
                        product.status === "critical" &&
                            "text-rose-600 bg-rose-50 border border-rose-100",
                        product.status === "warning" &&
                            "text-amber-600 bg-amber-50 border border-amber-100",
                    )}
                >
                    {#if product.status === "critical"}
                        <AlertCircle class="h-4.5 w-4.5" />
                    {:else}
                        <PackageOpen class="h-4.5 w-4.5" />
                    {/if}
                </div>

                <div class="flex-1 min-w-0">
                    <p
                        class="text-sm font-semibold text-foreground truncate group-hover:text-primary transition-colors"
                    >
                        {product.name}
                    </p>
                    <p class="text-xs text-muted-foreground">
                        Tối thiểu: <span class="font-medium text-foreground"
                            >{product.minStock}</span
                        >
                    </p>
                </div>

                <div
                    class={cn(
                        "text-xs font-bold px-3 py-1 rounded-full border shadow-sm",
                        product.status === "critical"
                            ? "bg-rose-50 text-rose-700 border-rose-200"
                            : "bg-amber-50 text-amber-700 border-amber-200",
                    )}
                >
                    {product.stock} còn lại
                </div>
            </div>
        {/each}
        <div class="p-2 bg-gray-50/30 border-t border-border/30">
            <Button
                variant="ghost"
                size="sm"
                class="w-full text-xs font-medium text-muted-foreground hover:text-primary h-8"
                >Báo cáo kho</Button
            >
        </div>
    </CardContent>
</Card>

// apps/web-old/components/dashboard/low-stock-alerts.tsx
"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { MoreHorizontal, Droplet, Sparkles } from "lucide-react";
import { LucideIcon } from "lucide-react";

interface LowStockItem {
  id: string;
  name: string;
  stock: number;
  unit: string;
  icon: LucideIcon;
  iconBg: string;
  iconColor: string;
}

const lowStockItems: LowStockItem[] = [
  {
    id: "1",
    name: "L'Oreal Shampoo Vol 2",
    stock: 2,
    unit: "chai",
    icon: Droplet,
    iconBg: "bg-red-100",
    iconColor: "text-red-500",
  },
  {
    id: "2",
    name: "Keratin Treatment Kit",
    stock: 3,
    unit: "bộ",
    icon: Sparkles,
    iconBg: "bg-yellow-100",
    iconColor: "text-yellow-600",
  },
];

export function LowStockAlerts() {
  return (
    <Card className="border border-gray-100 shadow-sm">
      <CardHeader className="flex flex-row items-center justify-between pb-4">
        <CardTitle className="text-lg font-semibold">Cảnh báo hết hàng</CardTitle>
        <Button variant="ghost" size="icon" className="h-8 w-8">
          <MoreHorizontal className="h-4 w-4" />
        </Button>
      </CardHeader>
      <CardContent className="space-y-4">
        {lowStockItems.map((item) => {
          const Icon = item.icon;
          return (
            <div
              key={item.id}
              className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg"
            >
              <div className={`p-2.5 rounded-lg ${item.iconBg}`}>
                <Icon className={`h-5 w-5 ${item.iconColor}`} />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-gray-900 truncate">
                  {item.name}
                </p>
                <p className="text-xs text-red-500">
                  Còn {item.stock} {item.unit}
                </p>
              </div>
              <Button
                variant="outline"
                size="sm"
                className="shrink-0 text-sm font-medium"
              >
                Đặt hàng
              </Button>
            </div>
          );
        })}
      </CardContent>
    </Card>
  );
}
