// apps/web/src/lib/components/layout/Header.svelte
<script lang="ts">
  import { Bell, Search, LogOut, Menu } from "@lucide/svelte";
  import { Input } from "$lib/components/ui/input";
  import { Button } from "$lib/components/ui/button";
  import { useSession, signOut } from "$lib/auth-client";
  import { goto } from "$app/navigation";

  interface Props {
    onMobileMenuOpen: () => void;
  }

  let { onMobileMenuOpen }: Props = $props();

  const session = useSession();
  let isLoggingOut = $state(false);

  async function handleLogout() {
    isLoggingOut = true;
    await signOut();
    goto("/signin");
  }

  function getInitials(name: string | null | undefined): string {
    if (!name) return $session.data?.user?.email?.charAt(0).toUpperCase() || "U";
    return name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2);
  }
</script>

<header
  class="sticky top-0 z-30 flex h-14 items-center gap-4 border-b border-border bg-background px-6"
>
  <!-- Mobile Menu Trigger -->
  <Button
    variant="ghost"
    size="icon"
    class="md:hidden -ml-2 h-8 w-8 text-muted-foreground"
    onclick={onMobileMenuOpen}
  >
    <Menu class="h-4 w-4" />
  </Button>

  <!-- Search -->
  <div class="flex-1 flex justify-start">
    <div class="relative w-full max-w-sm hidden md:block group">
      <Search
        class="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground group-focus-within:text-foreground transition-colors"
      />
      <Input
        type="search"
        placeholder="Tìm kiếm..."
        class="pl-9 h-9 w-64 bg-secondary/40 border-transparent focus:bg-background focus:border-border transition-all text-sm shadow-none rounded-md"
      />
    </div>
  </div>

  <!-- Right Actions -->
  <div class="flex items-center gap-2">
    <Button variant="ghost" size="icon" class="h-8 w-8 text-muted-foreground hover:text-foreground">
      <Bell class="h-4 w-4" />
    </Button>

    <div class="h-4 w-px bg-border mx-1"></div>

    <div class="flex items-center gap-2">
      <Button
        variant="ghost"
        size="icon"
        class="h-8 w-8 rounded-full border border-border bg-secondary text-secondary-foreground hover:text-foreground"
        onclick={() => goto("/profile")}
        title="Hồ sơ cá nhân"
      >
        <span class="sr-only">Hồ sơ cá nhân</span>
        {#if $session.data?.user?.image}
          <img
            src={$session.data.user.image}
            alt="Avatar"
            class="h-full w-full rounded-full object-cover"
          />
        {:else}
          <span class="text-[10px] font-semibold">
            {getInitials($session.data?.user?.name)}
          </span>
        {/if}
      </Button>
      <Button
        variant="ghost"
        size="icon"
        class="h-8 w-8 text-muted-foreground hover:text-foreground"
        onclick={handleLogout}
        disabled={isLoggingOut}
        title="Đăng xuất"
      >
        <LogOut class="h-4 w-4" />
      </Button>
    </div>
  </div>
</header>

// apps/web/components/layout/header.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, Search, LogOut, User, Settings } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { useUser } from "@/lib/hooks/use-user";
import { ProfileDialog } from "@/components/profile-dialog";
import { createClient } from "@/lib/supabase/client";

interface HeaderProps {
  onMobileMenuOpen: () => void;
}

export function Header({ onMobileMenuOpen }: HeaderProps) {
  const router = useRouter();
  const { user, profile, isLoading } = useUser();
  const [profileOpen, setProfileOpen] = useState(false);
  const [isLoggingOut, setIsLoggingOut] = useState(false);

  const handleLogout = async () => {
    setIsLoggingOut(true);
    const supabase = createClient();
    await supabase.auth.signOut();
    router.push("/login");
    router.refresh();
  };

  const getInitials = (name: string | null | undefined) => {
    if (!name) return user?.email?.charAt(0).toUpperCase() || "U";
    return name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2);
  };

  return (
    <>
      <header className="flex h-16 items-center justify-between border-b bg-white px-4 md:px-6 dark:bg-zinc-950">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" className="md:hidden" onClick={onMobileMenuOpen}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="h-6 w-6"
            >
              <line x1="3" x2="21" y1="6" y2="6" />
              <line x1="3" x2="21" y1="12" y2="12" />
              <line x1="3" x2="21" y1="18" y2="18" />
            </svg>
          </Button>
          <div className="flex w-full max-w-sm items-center gap-2">
            <div className="relative w-full hidden md:block">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Tìm kiếm khách hàng, lịch hẹn..."
                className="pl-9 w-64 lg:w-80 bg-zinc-50 dark:bg-zinc-900"
              />
            </div>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" className="relative">
            <Bell className="h-5 w-5" />
            <span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-600"></span>
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" className="relative h-8 w-8 rounded-full">
                <Avatar className="h-8 w-8">
                  <AvatarImage src={profile?.avatar_url || undefined} alt={profile?.full_name || "User"} />
                  <AvatarFallback>{getInitials(profile?.full_name)}</AvatarFallback>
                </Avatar>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent className="w-56" align="end" forceMount>
              <DropdownMenuLabel className="font-normal">
                <div className="flex flex-col space-y-1">
                  <p className="text-sm font-medium leading-none">
                    {profile?.full_name || "Chưa cập nhật"}
                  </p>
                  <p className="text-xs leading-none text-muted-foreground">
                    {user?.email}
                  </p>
                </div>
              </DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={() => setProfileOpen(true)}>
                <User className="mr-2 h-4 w-4" />
                Hồ sơ
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Settings className="mr-2 h-4 w-4" />
                Cài đặt
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem 
                onClick={handleLogout}
                disabled={isLoggingOut}
                className="text-destructive focus:text-destructive"
              >
                <LogOut className="mr-2 h-4 w-4" />
                {isLoggingOut ? "Đang đăng xuất..." : "Đăng xuất"}
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      
      <ProfileDialog open={profileOpen} onOpenChange={setProfileOpen} />
    </>
  );
}
