// apps/web-old/components/ui/date-picker.tsx
"use client"

import * as React from "react"
import { format } from "date-fns"
import { vi } from "date-fns/locale"
import { Calendar as CalendarIcon } from "lucide-react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Calendar } from "@/components/ui/calendar"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"

interface DatePickerProps {
  date: Date | undefined
  onSelect: (date: Date | undefined) => void
  placeholder?: string
  className?: string
}

export function DatePicker({ date, onSelect, placeholder = "Chọn ngày", className }: DatePickerProps) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button
          variant={"outline"}
          className={cn(
            "w-full justify-start text-left font-normal",
            !date && "text-muted-foreground",
            className
          )}
        >
          <CalendarIcon className="mr-2 h-4 w-4" />
          {date ? format(date, "dd/MM/yyyy", { locale: vi }) : <span>{placeholder}</span>}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-auto p-0" align="start">
        <Calendar
          mode="single"
          selected={date}
          onSelect={onSelect}
          initialFocus
          captionLayout="dropdown"
          fromYear={1940}
          toYear={new Date().getFullYear()}
        />
      </PopoverContent>
    </Popover>
  )
}

// apps/web/src/lib/components/ui/date-picker/date-picker.svelte
<script lang="ts">
    import {
        CalendarDate,
        DateFormatter,
        getLocalTimeZone,
        parseDate,
    } from "@internationalized/date";
    import { untrack } from "svelte";
    import Calendar from "$lib/components/ui/calendar/calendar.svelte";
    import * as Popover from "$lib/components/ui/popover/index.js";
    import { Button } from "$lib/components/ui/button/index.js";
    import { cn } from "$lib/utils";
    import CalendarIcon from "@lucide/svelte/icons/calendar";

    let {
        value = $bindable(""),
        placeholder = "Chọn ngày",
        class: className,
    } = $props<{
        value?: string;
        placeholder?: string;
        class?: string;
    }>();

    let date = $state<CalendarDate | undefined>(undefined);
    let isOpen = $state(false);

    const df = new DateFormatter("vi-VN", {
        dateStyle: "short",
    });

    // Sync value -> internal state
    $effect(() => {
        const val = value;
        untrack(() => {
            if (val) {
                try {
                    // Parse YYYY-MM-DD format
                    const parsed = parseDate(val);
                    if (
                        date?.year !== parsed.year ||
                        date?.month !== parsed.month ||
                        date?.day !== parsed.day
                    ) {
                        date = parsed;
                    }
                } catch {
                    date = undefined;
                }
            } else {
                date = undefined;
            }
        });
    });

    // Sync internal -> value
    $effect(() => {
        if (date) {
            const y = date.year;
            const m = date.month.toString().padStart(2, "0");
            const d = date.day.toString().padStart(2, "0");
            const newValue = `${y}-${m}-${d}`;

            untrack(() => {
                if (value !== newValue) {
                    value = newValue;
                }
            });
        }
    });

    let displayDate = $derived(
        date ? df.format(date.toDate(getLocalTimeZone())) : placeholder,
    );
</script>

<Popover.Root bind:open={isOpen}>
    <Popover.Trigger>
        {#snippet child({ props })}
            <Button
                {...props}
                variant="outline"
                class={cn(
                    "w-[140px] justify-start font-normal h-9 border-gray-200",
                    !date && "text-muted-foreground",
                    className,
                )}
            >
                <CalendarIcon class="mr-2 h-4 w-4" />
                {displayDate}
            </Button>
        {/snippet}
    </Popover.Trigger>
    <Popover.Content
        class="w-auto overflow-hidden p-0 rounded-lg"
        align="start"
    >
        <Calendar
            type="single"
            bind:value={date}
            onValueChange={() => {
                isOpen = false;
            }}
            captionLayout="dropdown"
        />
    </Popover.Content>
</Popover.Root>
