// apps/web/app/pages/login.vue
<script setup lang="ts">
definePageMeta({
  layout: false,
});

const client = useSupabaseClient();
const loading = ref(false);
const errorMessage = ref("");

const form = reactive({
  email: "",
  password: "",
});

const handleLogin = async () => {
  loading.value = true;
  errorMessage.value = "";

  const { error } = await client.auth.signInWithPassword({
    email: form.email,
    password: form.password,
  });

  if (error) {
    errorMessage.value = error.message;
    loading.value = false;
    return;
  }

  navigateTo("/");
};
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-muted/30 p-4">
    <UCard class="w-full max-w-md">
      <div class="text-center mb-6">
        <div
          class="h-16 w-16 rounded-xl bg-primary flex items-center justify-center mx-auto mb-4"
        >
          <span class="text-white font-bold text-2xl">S</span>
        </div>
        <h1 class="text-2xl font-bold">Đăng nhập</h1>
        <p class="text-muted mt-1">Chào mừng trở lại Salon Pro</p>
      </div>

      <UAlert
        v-if="errorMessage"
        color="error"
        icon="i-lucide-alert-circle"
        :title="errorMessage"
        class="mb-4"
      />

      <form @submit.prevent="handleLogin" class="space-y-4">
        <UFormField label="Email">
          <UInput
            v-model="form.email"
            type="email"
            placeholder="email@example.com"
            icon="i-lucide-mail"
            required
          />
        </UFormField>

        <UFormField label="Mật khẩu">
          <UInput
            v-model="form.password"
            type="password"
            placeholder="••••••••"
            icon="i-lucide-lock"
            required
          />
        </UFormField>

        <div class="flex items-center justify-between">
          <UCheckbox label="Ghi nhớ đăng nhập" />
          <NuxtLink
            to="/forgot-password"
            class="text-sm text-primary hover:underline"
          >
            Quên mật khẩu?
          </NuxtLink>
        </div>

        <UButton type="submit" block :loading="loading"> Đăng nhập </UButton>
      </form>

      <div class="mt-6 text-center text-sm text-muted">
        Chưa có tài khoản?
        <NuxtLink to="/signup" class="text-primary hover:underline font-medium">
          Đăng ký ngay
        </NuxtLink>
      </div>
    </UCard>
  </div>
</template>

// apps/web-svelte/src/routes/(auth)/login/+page.svelte
<script lang="ts">
    import {
        Card,
        CardContent,
        CardDescription,
        CardFooter,
        CardHeader,
        CardTitle,
    } from "$lib/components/ui/card";
    import { Button } from "$lib/components/ui/button";
    import { Input } from "$lib/components/ui/input";
    import { Label } from "$lib/components/ui/label";
    import LogIn from "lucide-svelte/icons/log-in";
    import Loader2 from "lucide-svelte/icons/loader-2";
    import { signIn } from "$lib/auth-client";
    import { goto } from "$app/navigation";

    let email = $state("");
    let password = $state("");
    let error = $state<string | null>(null);
    let isLoading = $state(false);

    // Form validation errors
    let emailError = $state<string | null>(null);
    let passwordError = $state<string | null>(null);

    function validateEmail(value: string): boolean {
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!value) {
            emailError = "Vui lòng nhập email";
            return false;
        }
        if (!emailRegex.test(value)) {
            emailError = "Email không hợp lệ";
            return false;
        }
        emailError = null;
        return true;
    }

    function validatePassword(value: string): boolean {
        if (!value) {
            passwordError = "Vui lòng nhập mật khẩu";
            return false;
        }
        if (value.length < 6) {
            passwordError = "Mật khẩu phải có ít nhất 6 ký tự";
            return false;
        }
        passwordError = null;
        return true;
    }

    async function handleSubmit(e: SubmitEvent) {
        e.preventDefault();

        const isEmailValid = validateEmail(email);
        const isPasswordValid = validatePassword(password);

        if (!isEmailValid || !isPasswordValid) {
            return;
        }

        isLoading = true;
        error = null;

        const result = await signIn.email({
            email,
            password,
        });

        if (result.error) {
            error =
                result.error.message ||
                "Đăng nhập thất bại. Vui lòng kiểm tra lại email và mật khẩu.";
            isLoading = false;
        } else {
            goto("/dashboard");
        }
    }
</script>

<Card class="shadow-2xl border-0">
    <CardHeader class="space-y-1 text-center">
        <div
            class="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-xl bg-primary text-primary-foreground"
        >
            <LogIn class="h-7 w-7" />
        </div>
        <CardTitle class="text-2xl font-bold">Đăng nhập</CardTitle>
        <CardDescription>
            Nhập email và mật khẩu để đăng nhập vào hệ thống
        </CardDescription>
    </CardHeader>
    <CardContent>
        {#if error}
            <div
                class="mb-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive border border-destructive/20"
            >
                {error}
            </div>
        {/if}
        <form onsubmit={handleSubmit} class="space-y-4">
            <div class="space-y-2">
                <Label for="email">Email</Label>
                <Input
                    id="email"
                    type="email"
                    placeholder="email@example.com"
                    autocomplete="email"
                    disabled={isLoading}
                    bind:value={email}
                    onblur={() => validateEmail(email)}
                />
                {#if emailError}
                    <p class="text-sm text-destructive">{emailError}</p>
                {/if}
            </div>
            <div class="space-y-2">
                <Label for="password">Mật khẩu</Label>
                <Input
                    id="password"
                    type="password"
                    placeholder="••••••••"
                    autocomplete="current-password"
                    disabled={isLoading}
                    bind:value={password}
                    onblur={() => validatePassword(password)}
                />
                {#if passwordError}
                    <p class="text-sm text-destructive">{passwordError}</p>
                {/if}
            </div>
            <Button type="submit" class="w-full" size="lg" disabled={isLoading}>
                {#if isLoading}
                    <Loader2 class="mr-2 h-4 w-4 animate-spin" />
                    Đang đăng nhập...
                {:else}
                    Đăng nhập
                {/if}
            </Button>
        </form>
    </CardContent>
    <CardFooter class="flex flex-col space-y-4">
        <div class="text-center text-sm text-muted-foreground">
            Chưa có tài khoản?
            <a href="/signup" class="text-primary font-medium hover:underline">
                Đăng ký ngay
            </a>
        </div>
    </CardFooter>
</Card>
