// apps/web-old/components/dashboard/today-schedule.tsx
"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import Link from "next/link";

interface Appointment {
  id: string;
  time: string;
  period: "AM" | "PM";
  clientName: string;
  service: string;
  staff: string;
  status: "confirmed" | "check-in" | "pending" | "available";
}

const todayAppointments: Appointment[] = [
  {
    id: "1",
    time: "10:00",
    period: "AM",
    clientName: "Nguyễn Thị Lan",
    service: "Cắt & Sấy tóc",
    staff: "Minh",
    status: "confirmed",
  },
  {
    id: "2",
    time: "11:30",
    period: "AM",
    clientName: "Trần Văn Hùng",
    service: "Nhuộm tóc",
    staff: "Linh",
    status: "check-in",
  },
  {
    id: "3",
    time: "01:00",
    period: "PM",
    clientName: "Phạm Thị Mai",
    service: "Cắt râu",
    staff: "David",
    status: "pending",
  },
  {
    id: "4",
    time: "02:15",
    period: "PM",
    clientName: "",
    service: "",
    staff: "",
    status: "available",
  },
];

const statusConfig = {
  confirmed: {
    label: "Đã xác nhận",
    className: "bg-green-100 text-green-700 hover:bg-green-100",
  },
  "check-in": {
    label: "Đã đến",
    className: "bg-orange-100 text-orange-700 hover:bg-orange-100",
  },
  pending: {
    label: "Chờ duyệt",
    className: "bg-gray-100 text-gray-600 hover:bg-gray-100",
  },
  available: {
    label: "",
    className: "",
  },
};

export function TodaySchedule() {
  return (
    <Card className="border border-gray-100 shadow-sm h-full">
      <CardHeader className="flex flex-row items-center justify-between pb-4">
        <CardTitle className="text-lg font-semibold">Lịch hẹn hôm nay</CardTitle>
        <Link
          href="/bookings"
          className="text-sm text-purple-600 hover:text-purple-700 font-medium"
        >
          Xem tất cả
        </Link>
      </CardHeader>
      <CardContent className="space-y-4">
        {todayAppointments.map((appointment) => (
          <div
            key={appointment.id}
            className="flex items-start gap-4 pb-4 border-b border-gray-100 last:border-0 last:pb-0"
          >
            {/* Time */}
            <div className="text-center min-w-[50px]">
              <p className="text-sm font-semibold text-gray-900">{appointment.time}</p>
              <p className="text-xs text-muted-foreground">{appointment.period}</p>
            </div>

            {/* Divider line */}
            <div className="w-px h-12 bg-purple-300 self-center" />

            {/* Content */}
            <div className="flex-1 min-w-0">
              {appointment.status === "available" ? (
                <div className="py-2">
                  <p className="text-sm font-medium text-gray-600">Khung giờ trống</p>
                  <p className="text-xs text-muted-foreground">30 phút</p>
                </div>
              ) : (
                <>
                  <p className="text-sm font-semibold text-gray-900 truncate">
                    {appointment.clientName}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    {appointment.service} • {appointment.staff}
                  </p>
                </>
              )}
            </div>

            {/* Status Badge */}
            {appointment.status !== "available" && (
              <Badge
                variant="secondary"
                className={cn(
                  "text-xs font-medium shrink-0",
                  statusConfig[appointment.status].className
                )}
              >
                {statusConfig[appointment.status].label}
              </Badge>
            )}
          </div>
        ))}
      </CardContent>
    </Card>
  );
}

// apps/web/src/lib/components/dashboard/TodaySchedule.svelte
<script lang="ts">
    import {
        Card,
        CardContent,
        CardHeader,
        CardTitle,
    } from "$lib/components/ui/card";
    import { Clock, ArrowUpRight, CalendarRange } from "@lucide/svelte";
    import { cn } from "$lib/utils";
    import { Button } from "$lib/components/ui/button";

    // Mock data for today's schedule
    const appointments = [
        {
            id: 1,
            time: "09:00",
            customer: "Nguyễn Văn A",
            service: "Cắt tóc nam",
            staff: "Trần B",
            status: "confirmed",
        },
        {
            id: 2,
            time: "09:30",
            customer: "Trần Thị C",
            service: "Gội đầu massage",
            staff: "Lê D",
            status: "confirmed",
        },
        {
            id: 3,
            time: "10:00",
            customer: "Lê Văn E",
            service: "Nhuộm tóc",
            staff: "Trần B",
            status: "pending",
        },
        {
            id: 4,
            time: "10:30",
            customer: "Phạm Thị F",
            service: "Cắt tóc nữ",
            staff: "Nguyễn G",
            status: "confirmed",
        },
        {
            id: 5,
            time: "11:00",
            customer: "Hoàng Văn H",
            service: "Uốn tóc",
            staff: "Lê D",
            status: "confirmed",
        },
    ];
</script>

<Card
    class="h-full border border-border/60 shadow-sm rounded-xl bg-white overflow-hidden"
>
    <CardHeader
        class="flex flex-row items-center justify-between pb-3 border-b border-border/30 space-y-0 bg-gray-50/30"
    >
        <CardTitle class="text-sm font-semibold text-foreground tracking-tight">
            Lịch hôm nay
        </CardTitle>
        <Button
            variant="ghost"
            size="icon"
            class="h-8 w-8 -mr-2 text-primary hover:bg-primary/5 hover:text-primary"
        >
            <CalendarRange class="h-4 w-4" />
        </Button>
    </CardHeader>
    <CardContent class="p-0">
        {#each appointments as appointment, index}
            <div
                class={cn(
                    "flex items-center gap-4 px-5 py-4 hover:bg-purple-50/30 transition-colors border-b border-border/30 last:border-0 group",
                )}
            >
                <!-- Time Badge -->
                <div
                    class="px-2 py-1 rounded-md bg-gray-100 text-xs font-bold text-gray-600 group-hover:bg-primary/10 group-hover:text-primary transition-colors"
                >
                    {appointment.time}
                </div>

                <!-- Content -->
                <div class="flex-1 min-w-0">
                    <p
                        class="text-sm font-semibold text-foreground truncate group-hover:text-primary transition-colors"
                    >
                        {appointment.customer}
                    </p>
                    <p class="text-xs text-muted-foreground truncate">
                        {appointment.service}
                    </p>
                </div>

                <!-- Staff -->
                <div
                    class="text-xs font-medium text-muted-foreground hidden sm:block bg-gray-50 px-2 py-1 rounded-full border border-gray-200"
                >
                    {appointment.staff}
                </div>

                <!-- Status indicator -->
                <div
                    class={cn(
                        "h-2 w-2 rounded-full ring-2 ring-white shadow-sm",
                        appointment.status === "confirmed"
                            ? "bg-emerald-500"
                            : "bg-amber-500",
                    )}
                ></div>
            </div>
        {/each}
        <div class="p-2 bg-gray-50/30 border-t border-border/30">
            <Button
                variant="ghost"
                size="sm"
                class="w-full text-xs font-medium text-muted-foreground hover:text-primary h-8"
                >Xem lịch</Button
            >
        </div>
    </CardContent>
</Card>
