// apps/web-svelte/src/routes/(dashboard)/invoices/+page.svelte
<script lang="ts">
    import { Card } from "$lib/components/ui/card";
    import { Button } from "$lib/components/ui/button";
    import { Input } from "$lib/components/ui/input";
    import { Plus, Search, Receipt } from "@lucide/svelte";
    import { cn } from "$lib/utils";

    // Mock data
    const invoices = [
        {
            id: "HD001",
            customerName: "Nguyễn Văn A",
            date: "12/01/2026",
            services: ["Cắt tóc", "Gội đầu"],
            total: 130000,
            status: "Paid",
        },
        {
            id: "HD002",
            customerName: "Trần Thị B",
            date: "12/01/2026",
            services: ["Nhuộm tóc"],
            total: 350000,
            status: "Paid",
        },
        {
            id: "HD003",
            customerName: "Lê Văn C",
            date: "11/01/2026",
            services: ["Uốn tóc", "Chăm sóc"],
            total: 700000,
            status: "Pending",
        },
        {
            id: "HD004",
            customerName: "Phạm Thị D",
            date: "11/01/2026",
            services: ["Cắt tóc nữ"],
            total: 120000,
            status: "Paid",
        },
        {
            id: "HD005",
            customerName: "Hoàng Văn E",
            date: "10/01/2026",
            services: ["Duỗi tóc"],
            total: 600000,
            status: "Cancelled",
        },
    ];

    const statusStyles: Record<string, string> = {
        Paid: "bg-green-100 text-green-700",
        Pending: "bg-yellow-100 text-yellow-700",
        Cancelled: "bg-red-100 text-red-700",
    };

    const statusLabels: Record<string, string> = {
        Paid: "Đã thanh toán",
        Pending: "Chờ thanh toán",
        Cancelled: "Đã hủy",
    };

    function formatPrice(price: number) {
        return new Intl.NumberFormat("vi-VN").format(price) + "đ";
    }
</script>

<svelte:head>
    <title>Hóa đơn | Salon Pro</title>
</svelte:head>

<div class="flex flex-col gap-6">
    <!-- Header -->
    <div
        class="flex flex-col sm:flex-row sm:items-center justify-between gap-4"
    >
        <div>
            <h1 class="text-2xl font-bold tracking-tight">Hóa đơn</h1>
            <p class="text-muted-foreground">Quản lý hóa đơn và thanh toán</p>
        </div>
        <Button class="bg-purple-600 hover:bg-purple-700">
            <Plus class="h-4 w-4 mr-2" />
            Tạo hóa đơn
        </Button>
    </div>

    <!-- Search -->
    <div class="flex items-center gap-4">
        <div class="relative flex-1 max-w-sm">
            <Search
                class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"
            />
            <Input
                type="search"
                placeholder="Tìm kiếm hóa đơn..."
                class="pl-9"
            />
        </div>
    </div>

    <!-- Invoices Table -->
    <Card>
        <div class="overflow-x-auto">
            <table class="w-full">
                <thead class="border-b">
                    <tr>
                        <th
                            class="px-4 py-3 text-left text-sm font-medium text-muted-foreground"
                            >Mã hóa đơn</th
                        >
                        <th
                            class="px-4 py-3 text-left text-sm font-medium text-muted-foreground"
                            >Khách hàng</th
                        >
                        <th
                            class="px-4 py-3 text-left text-sm font-medium text-muted-foreground"
                            >Ngày</th
                        >
                        <th
                            class="px-4 py-3 text-left text-sm font-medium text-muted-foreground"
                            >Dịch vụ</th
                        >
                        <th
                            class="px-4 py-3 text-left text-sm font-medium text-muted-foreground"
                            >Tổng tiền</th
                        >
                        <th
                            class="px-4 py-3 text-left text-sm font-medium text-muted-foreground"
                            >Trạng thái</th
                        >
                    </tr>
                </thead>
                <tbody class="divide-y">
                    {#each invoices as invoice}
                        <tr class="hover:bg-muted/50">
                            <td class="px-4 py-3">
                                <div class="flex items-center gap-2">
                                    <Receipt
                                        class="h-4 w-4 text-muted-foreground"
                                    />
                                    <span class="text-sm font-medium"
                                        >{invoice.id}</span
                                    >
                                </div>
                            </td>
                            <td class="px-4 py-3 text-sm"
                                >{invoice.customerName}</td
                            >
                            <td class="px-4 py-3 text-sm text-muted-foreground"
                                >{invoice.date}</td
                            >
                            <td class="px-4 py-3 text-sm"
                                >{invoice.services.join(", ")}</td
                            >
                            <td class="px-4 py-3 text-sm font-medium"
                                >{formatPrice(invoice.total)}</td
                            >
                            <td class="px-4 py-3">
                                <span
                                    class={cn(
                                        "px-2 py-1 rounded-full text-xs font-medium",
                                        statusStyles[invoice.status],
                                    )}
                                >
                                    {statusLabels[invoice.status]}
                                </span>
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
    </Card>
</div>

// apps/web/app/pages/invoices.vue
<script setup lang="ts">
definePageMeta({
  layout: "dashboard",
});

const client = useSupabaseClient();

const { data: invoices, status } = await useAsyncData("invoices", async () => {
  const { data, error } = await client
    .from("invoice")
    .select("*, customer(name, phone)")
    .order("created_at", { ascending: false });

  if (error) throw error;
  return data || [];
});

const searchQuery = ref("");

const filteredInvoices = computed(() => {
  if (!invoices.value) return [];
  const query = searchQuery.value.toLowerCase();
  return invoices.value.filter(
    (invoice: any) =>
      invoice.customer?.name?.toLowerCase().includes(query) ||
      invoice.invoice_number?.toLowerCase().includes(query)
  );
});

const formatPrice = (price: number) => {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
  }).format(price);
};

const formatDate = (date: string) => new Date(date).toLocaleDateString("vi-VN");

const getStatusBadge = (status: string) => {
  switch (status) {
    case "paid":
      return { color: "success" as const, label: "Đã thanh toán" };
    case "pending":
      return { color: "warning" as const, label: "Chờ thanh toán" };
    case "cancelled":
      return { color: "error" as const, label: "Đã hủy" };
    default:
      return { color: "neutral" as const, label: status };
  }
};
</script>

<template>
  <div class="flex flex-col gap-6">
    <!-- Header -->
    <div class="flex flex-col gap-4">
      <h1 class="text-2xl font-bold tracking-tight">Hóa đơn</h1>
      <div class="flex flex-col sm:flex-row gap-4 justify-between">
        <UInput
          v-model="searchQuery"
          placeholder="Tìm kiếm hóa đơn..."
          icon="i-lucide-search"
          class="max-w-sm"
        />
        <UButton icon="i-lucide-plus">Tạo hóa đơn</UButton>
      </div>
    </div>

    <!-- Table -->
    <UCard :ui="{ body: 'p-0' }">
      <UTable
        :loading="status === 'pending'"
        :data="filteredInvoices"
        :columns="[
          { key: 'invoice_number', label: 'Mã hóa đơn' },
          { key: 'customer', label: 'Khách hàng' },
          { key: 'total_amount', label: 'Tổng tiền' },
          { key: 'status', label: 'Trạng thái' },
          { key: 'created_at', label: 'Ngày tạo' },
          { key: 'actions', label: 'Thao tác' },
        ]"
      >
        <template #invoice_number-cell="{ row }">
          <span class="font-medium font-mono">{{
            row.original.invoice_number || row.original.id?.slice(0, 8)
          }}</span>
        </template>
        <template #customer-cell="{ row }">
          <div>
            <div class="font-medium">
              {{ row.original.customer?.name || "-" }}
            </div>
            <div class="text-sm text-muted">
              {{ row.original.customer?.phone }}
            </div>
          </div>
        </template>
        <template #total_amount-cell="{ row }">
          <span class="font-semibold">{{
            formatPrice(row.original.total_amount)
          }}</span>
        </template>
        <template #status-cell="{ row }">
          <UBadge :color="getStatusBadge(row.original.status).color">
            {{ getStatusBadge(row.original.status).label }}
          </UBadge>
        </template>
        <template #created_at-cell="{ row }">
          {{ formatDate(row.original.created_at) }}
        </template>
        <template #actions-cell>
          <div class="flex items-center gap-1">
            <UButton
              icon="i-lucide-eye"
              color="neutral"
              variant="ghost"
              size="xs"
              title="Xem chi tiết"
            />
            <UButton
              icon="i-lucide-printer"
              color="neutral"
              variant="ghost"
              size="xs"
              title="In hóa đơn"
            />
          </div>
        </template>
        <template #empty>
          <div class="text-center py-8 text-muted">
            {{
              searchQuery ? "Không tìm thấy hóa đơn nào" : "Chưa có hóa đơn nào"
            }}
          </div>
        </template>
      </UTable>
    </UCard>
  </div>
</template>
