// apps/web/app/(dashboard)/page.tsx
"use client";

import { useState, useEffect } from "react";
import { StatsCard } from "@/components/dashboard/stats-card";
import { RevenueChart } from "@/components/dashboard/revenue-chart";
import { TodaySchedule } from "@/components/dashboard/today-schedule";
import { TopStylists } from "@/components/dashboard/top-stylists";
import { LowStockAlerts } from "@/components/dashboard/low-stock-alerts";
import { Button } from "@/components/ui/button";
import {
  CalendarDays,
  Users,
  DollarSign,
  TrendingUp,
  Plus,
} from "lucide-react";

export default function Home() {
  const [formattedDate, setFormattedDate] = useState("");

  useEffect(() => {
    const today = new Date();
    setFormattedDate(
      today.toLocaleDateString("vi-VN", {
        weekday: "long",
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    );
  }, []);

  return (
    <div className="flex flex-col gap-6">
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">
            Chào mừng trở lại, Salon Pro
          </h1>
          <p className="text-muted-foreground">
            Đây là những gì đang xảy ra tại salon của bạn hôm nay.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-sm text-muted-foreground capitalize">
            {formattedDate}
          </span>
          <Button className="bg-purple-600 hover:bg-purple-700">
            <Plus className="h-4 w-4 mr-2" />
            Tạo lịch hẹn mới
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatsCard
          title="Tổng doanh thu"
          value="12.450.000đ"
          description="so với tháng trước"
          icon={DollarSign}
          trend="up"
          trendValue="+12%"
          iconBgColor="bg-purple-100"
          iconColor="text-purple-600"
        />
        <StatsCard
          title="Lịch hẹn hôm nay"
          value="45"
          description="so với hôm qua"
          icon={CalendarDays}
          trend="up"
          trendValue="+5%"
          iconBgColor="bg-blue-100"
          iconColor="text-blue-600"
        />
        <StatsCard
          title="Khách hàng mới"
          value="8"
          description="so với tuần trước"
          icon={Users}
          trend="up"
          trendValue="+2%"
          iconBgColor="bg-green-100"
          iconColor="text-green-600"
        />
        <StatsCard
          title="Giá trị trung bình"
          value="85.000đ"
          description="so với tháng trước"
          icon={TrendingUp}
          trend="up"
          trendValue="+1.5%"
          iconBgColor="bg-orange-100"
          iconColor="text-orange-600"
        />
      </div>

      {/* Main Content Grid */}
      <div className="grid gap-6 lg:grid-cols-5">
        {/* Revenue Chart - Takes 3 columns */}
        <div className="lg:col-span-3">
          <RevenueChart />
        </div>
        {/* Today's Schedule - Takes 2 columns */}
        <div className="lg:col-span-2">
          <TodaySchedule />
        </div>
      </div>

      {/* Bottom Section */}
      <div className="grid gap-6 md:grid-cols-2">
        <TopStylists />
        <LowStockAlerts />
      </div>
    </div>
  );
}

// apps/web/src/routes/(dashboard)/+page.svelte
<script lang="ts">
    import { Card, CardContent } from "$lib/components/ui/card";
    import { Button } from "$lib/components/ui/button";
    import {
        CalendarDays,
        Users,
        DollarSign,
        TrendingUp,
        Plus,
        BarChart3,
    } from "@lucide/svelte";
    import StatsCard from "$lib/components/dashboard/StatsCard.svelte";
    import TodaySchedule from "$lib/components/dashboard/TodaySchedule.svelte";
    import TopStylists from "$lib/components/dashboard/TopStylists.svelte";
    import LowStockAlerts from "$lib/components/dashboard/LowStockAlerts.svelte";

    let formattedDate = $state("");

    $effect(() => {
        const today = new Date();
        formattedDate = today.toLocaleDateString("vi-VN", {
            weekday: "long",
            day: "numeric",
            month: "long",
            year: "numeric",
        });
    });
</script>

<svelte:head>
    <title>Tổng quan | SupaSalon</title>
</svelte:head>

<div class="flex flex-col gap-6 max-w-[1600px] mx-auto w-full">
    <!-- Header Section -->
    <div
        class="flex flex-col sm:flex-row sm:items-center justify-between gap-4"
    >
        <div>
            <h1 class="text-2xl font-bold tracking-tight text-foreground">
                Tổng quan
            </h1>
            <p class="text-muted-foreground mt-1">
                Hiệu suất salon của bạn trong nháy mắt.
            </p>
        </div>
        <div class="flex items-center gap-3">
            <span
                class="text-sm font-medium text-muted-foreground hidden sm:block border border-border px-3 py-1.5 rounded-md bg-white"
            >
                {formattedDate}
            </span>
            <Button class="btn-clean shadow-sm">
                <Plus class="h-4 w-4 mr-2" />
                Đặt lịch mới
            </Button>
        </div>
    </div>

    <!-- Stats Cards -->
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatsCard
            title="Tổng doanh thu"
            value="12.450.000 ₫"
            description="so với tháng trước"
            icon={DollarSign}
            trend="up"
            trendValue="+12%"
        />
        <StatsCard
            title="Cuộc hẹn"
            value="45"
            description="so với hôm qua"
            icon={CalendarDays}
            trend="up"
            trendValue="+5%"
        />
        <StatsCard
            title="Khách hàng mới"
            value="8"
            description="so với tuần trước"
            icon={Users}
            trend="up"
            trendValue="+2%"
        />
        <StatsCard
            title="Hóa đơn trung bình"
            value="850.000 ₫"
            description="so với tháng trước"
            icon={TrendingUp}
            trend="up"
            trendValue="+1.5%"
        />
    </div>

    <!-- Main Content Grid -->
    <div class="grid gap-6 lg:grid-cols-3">
        <!-- Revenue Chart Placeholder - Takes 2 columns -->
        <div class="lg:col-span-2">
            <Card
                class="h-full border border-border shadow-sm rounded-lg bg-card"
            >
                <CardContent class="p-6">
                    <div class="flex items-center justify-between mb-6">
                        <div class="flex items-center gap-2">
                            <BarChart3 class="h-4 w-4 text-muted-foreground" />
                            <h3 class="text-sm font-semibold text-foreground">
                                Biểu đồ doanh thu
                            </h3>
                        </div>
                        <div class="flex gap-1 p-1 bg-muted/50 rounded-lg">
                            <button
                                class="text-xs px-3 py-1 rounded-md bg-background shadow-sm text-foreground font-medium transition-all"
                                >Tuần</button
                            >
                            <button
                                class="text-xs px-3 py-1 rounded-md hover:bg-background/50 text-muted-foreground font-medium transition-all"
                                >Tháng</button
                            >
                            <button
                                class="text-xs px-3 py-1 rounded-md hover:bg-background/50 text-muted-foreground font-medium transition-all"
                                >Năm</button
                            >
                        </div>
                    </div>

                    <!-- Clean Minimalist Chart Placeholder -->
                    <div
                        class="h-64 flex items-end justify-between gap-2 px-2 pb-4"
                    >
                        {#each [40, 65, 45, 80, 55, 90, 75] as height}
                            <div
                                class="w-full bg-secondary hover:bg-primary/80 transition-colors rounded-t-sm relative group"
                                style="height: {height}%"
                            >
                                <div
                                    class="absolute -top-8 left-1/2 -translate-x-1/2 bg-popover text-popover-foreground text-xs py-1 px-2 rounded shadow-sm opacity-0 group-hover:opacity-100 transition-opacity border border-border pointer-events-none"
                                >
                                    {height * 10}.000 ₫
                                </div>
                            </div>
                        {/each}
                    </div>
                    <div
                        class="flex justify-between px-2 pt-2 border-t border-border/40 text-xs text-muted-foreground font-medium"
                    >
                        <span>T2</span><span>T3</span><span>T4</span><span
                            >T5</span
                        ><span>T6</span><span>T7</span><span>CN</span>
                    </div>
                </CardContent>
            </Card>
        </div>

        <!-- Today's Schedule - Takes 1 column -->
        <div class="lg:col-span-1">
            <TodaySchedule />
        </div>
    </div>

    <!-- Bottom Section -->
    <div class="grid gap-6 md:grid-cols-2">
        <TopStylists />
        <LowStockAlerts />
    </div>
</div>
