// apps/web/components/layout/sidebar.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  LayoutDashboard,
  CalendarDays,
  Users,
  Receipt,
  UserCog,
  Settings,
  Scissors,
  PanelLeftClose,
  PanelLeft,
  Package,
} from "lucide-react";

const sidebarItems = [
  {
    title: "Tổng quan",
    href: "/",
    icon: LayoutDashboard,
  },
  {
    title: "Lịch hẹn",
    href: "/bookings",
    icon: CalendarDays,
  },
  {
    title: "Dịch vụ",
    href: "/services",
    icon: Scissors,
  },
  {
    title: "Sản phẩm",
    href: "/products",
    icon: Package,
  },
  {
    title: "Khách hàng",
    href: "/customers",
    icon: Users,
  },
  {
    title: "Hóa đơn",
    href: "/invoices",
    icon: Receipt,
  },
  {
    title: "Nhân viên",
    href: "/employees",
    icon: UserCog,
  },
  {
    title: "Cài đặt",
    href: "/settings",
    icon: Settings,
  },
];

interface SidebarProps {
  className?: string;
  collapsed?: boolean;
  onToggle?: () => void;
}

export function Sidebar({ className, collapsed = false, onToggle }: SidebarProps) {
  const pathname = usePathname();
  const [isHeaderHovered, setIsHeaderHovered] = useState(false);

  return (
    <div
      className={cn(
        "flex h-full flex-col border-r border-sidebar-border bg-sidebar text-sidebar-foreground transition-all duration-300",
        collapsed ? "w-16" : "w-64",
        className
      )}
    >
      {/* Header with Logo / Toggle */}
      <div
        className={cn(
          "flex h-16 items-center border-b border-sidebar-border transition-all px-6",
          collapsed ? "justify-center" : "justify-between"
        )}
        onMouseEnter={() => setIsHeaderHovered(true)}
        onMouseLeave={() => setIsHeaderHovered(false)}
      >
        {collapsed ? (
          // Collapsed state: show logo, on hover show toggle icon
          <Button
            variant="ghost"
            size="icon"
            onClick={onToggle}
            className="h-10 w-10 p-0"
            title="Mở rộng menu"
          >
            {isHeaderHovered ? (
              <PanelLeft className="h-6 w-6 text-primary" />
            ) : (
              <Image src="/logo.png" alt="Logo" width={40} height={40} />
            )}
          </Button>
        ) : (
          // Expanded state: always show logo AND toggle icon
          <>
            <Image src="/logo.png" alt="Logo" width={40} height={40} />
            {onToggle && (
              <Button
                variant="ghost"
                size="icon"
                onClick={onToggle}
                className="h-8 w-8"
                title="Thu gọn menu"
              >
                <PanelLeftClose className="h-4 w-4" />
              </Button>
            )}
          </>
        )}
      </div>

      {/* Navigation */}
      <nav className="flex-1 space-y-2 p-4">
        {sidebarItems.map((item) => (
          <Link
            key={item.href}
            href={item.href}
            className={cn(
              "flex items-center gap-4 rounded-xl px-4 py-3 text-sm font-medium transition-colors",
              pathname === item.href
                ? "bg-sidebar-accent text-sidebar-accent-foreground shadow-sm"
                : "text-sidebar-foreground hover:bg-sidebar-accent/50 hover:text-sidebar-accent-foreground",
              collapsed ? "justify-center px-2 py-2" : ""
            )}
            title={collapsed ? item.title : undefined}
          >
            <item.icon className="h-5 w-5 shrink-0" />
            {!collapsed && <span className="truncate text-base">{item.title}</span>}
          </Link>
        ))}
      </nav>

      {/* User section */}
      <div className={cn("border-t border-sidebar-border p-4", collapsed ? "flex justify-center p-2" : "")}>
        <div className={cn("flex items-center gap-3", collapsed ? "justify-center" : "")}>
          <div className="h-8 w-8 rounded-full bg-sidebar-accent/50 shrink-0"></div>
          {!collapsed && (
            <div className="flex flex-col overflow-hidden">
              <span className="text-sm font-medium text-foreground truncate">Admin User</span>
              <span className="text-xs text-muted-foreground truncate">admin@salon.com</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// apps/web/app/components/layout/Sidebar.vue
<script setup lang="ts">
const props = defineProps<{
  collapsed?: boolean;
}>();

const emit = defineEmits<{
  toggle: [];
}>();

const route = useRoute();

const sidebarItems = [
  { title: "Tổng quan", href: "/", icon: "i-lucide-layout-dashboard" },
  { title: "Lịch hẹn", href: "/bookings", icon: "i-lucide-calendar-days" },
  { title: "Dịch vụ", href: "/services", icon: "i-lucide-scissors" },
  { title: "Sản phẩm", href: "/products", icon: "i-lucide-package" },
  { title: "Khách hàng", href: "/customers", icon: "i-lucide-users" },
  { title: "Hóa đơn", href: "/invoices", icon: "i-lucide-receipt" },
  { title: "Nhân viên", href: "/employees", icon: "i-lucide-user-cog" },
  { title: "Cài đặt", href: "/settings", icon: "i-lucide-settings" },
];

const isActive = (href: string) => {
  if (href === "/") return route.path === "/";
  return route.path.startsWith(href);
};
</script>

<template>
  <div
    class="flex h-full flex-col border-r border-default bg-elevated transition-all duration-300"
    :class="collapsed ? 'w-16' : 'w-64'"
  >
    <!-- Header with Logo / Toggle -->
    <div
      class="flex h-16 items-center border-b border-default px-4"
      :class="collapsed ? 'justify-center' : 'justify-between'"
    >
      <template v-if="collapsed">
        <UButton
          icon="i-lucide-panel-left"
          color="neutral"
          variant="ghost"
          size="lg"
          @click="emit('toggle')"
          title="Mở rộng menu"
        />
      </template>
      <template v-else>
        <div class="flex items-center gap-2">
          <div
            class="h-10 w-10 rounded-lg bg-primary flex items-center justify-center"
          >
            <span class="text-white font-bold text-lg">S</span>
          </div>
          <span class="font-semibold">Salon Pro</span>
        </div>
        <UButton
          icon="i-lucide-panel-left-close"
          color="neutral"
          variant="ghost"
          size="sm"
          @click="emit('toggle')"
          title="Thu gọn menu"
        />
      </template>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 space-y-1 p-3 overflow-y-auto">
      <NuxtLink
        v-for="item in sidebarItems"
        :key="item.href"
        :to="item.href"
        class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-colors"
        :class="[
          isActive(item.href)
            ? 'bg-primary/10 text-primary'
            : 'text-muted hover:bg-elevated hover:text-default',
          collapsed ? 'justify-center px-2' : '',
        ]"
        :title="collapsed ? item.title : undefined"
      >
        <UIcon :name="item.icon" class="h-5 w-5 shrink-0" />
        <span v-if="!collapsed" class="truncate">{{ item.title }}</span>
      </NuxtLink>
    </nav>

    <!-- User section -->
    <div
      class="border-t border-default p-3"
      :class="collapsed ? 'flex justify-center' : ''"
    >
      <div
        class="flex items-center gap-3"
        :class="collapsed ? 'justify-center' : ''"
      >
        <UAvatar size="sm" alt="User" />
        <div v-if="!collapsed" class="flex flex-col overflow-hidden">
          <span class="text-sm font-medium truncate">Admin User</span>
          <span class="text-xs text-muted truncate">admin@salon.com</span>
        </div>
      </div>
    </div>
  </div>
</template>
